"use client";
import {useLayoutEffect,useRef} from "react";
import gsap from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";
import MagneticButton from "@/components/ui/MagneticButton";
gsap.registerPlugin(ScrollTrigger);
export default function Hero(){
 const section=useRef<HTMLElement>(null),video=useRef<HTMLVideoElement>(null);
 useLayoutEffect(()=>{const ctx=gsap.context(()=>{gsap.timeline({delay:.25}).from(".hero-kicker,.hero-title,.hero-copy,.hero-actions",{y:35,opacity:0,stagger:.08,duration:1,ease:"power3.out"});if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;ScrollTrigger.create({trigger:section.current,start:"top top",end:"+=120%",pin:true,scrub:true,onUpdate:self=>{const v=video.current;if(v?.readyState&&v.duration) v.currentTime=self.progress*v.duration}});gsap.to(video.current,{scale:1.08,ease:"none",scrollTrigger:{trigger:section.current,start:"top top",end:"bottom top",scrub:true}})},section);return()=>ctx.revert()},[]);
 return <section ref={section} className="relative flex min-h-screen items-end overflow-hidden bg-[#041326] text-white grain"><video ref={video} className="hero-video absolute inset-0 h-full w-full object-cover" poster="/video/hero_poster1.jpeg" autoPlay muted playsInline preload="metadata"><source src="/video/hero.mp4" type="video/mp4"/></video><div className="hero-noise absolute inset-0"/><div className="relative z-10 w-full pb-14 pt-40 md:pb-24"><div className="container"><p className="hero-kicker eyebrow mb-5">Built for Island Life · St. Vincent & the Grenadines</p><h1 className="hero-title max-w-5xl text-balance text-5xl font-black leading-[.92] tracking-[-.055em] md:text-[clamp(4.8rem,9vw,8.6rem)]">Modern homes.<br/><span className="text-[#c99227]">Island living.</span></h1><p className="hero-copy mt-7 max-w-2xl text-lg leading-relaxed text-white/80 md:text-xl">Affordable, modern and sustainable living solutions — thoughtfully designed for your lifestyle and budget.</p><div className="hero-actions mt-8 flex flex-wrap gap-3"><MagneticButton href="#models" className="rounded-full bg-[#c99227] px-7 py-3.5 font-extrabold text-[#061b33]">Explore homes <span className="ml-2">↓</span></MagneticButton><MagneticButton href="#contact" className="rounded-full border border-white/45 bg-white/5 px-7 py-3.5 font-extrabold backdrop-blur">Get your free quote ↗</MagneticButton></div><div className="mt-12 flex flex-wrap items-center gap-5 text-xs font-bold uppercase tracking-[.18em] text-white/55"><span>Affordable</span><span>Premium quality</span><span>Fast delivery</span><span>Customizable</span></div></div></div></section>}
